package com.agechecked.hooks;

import com.agechecked.config.ConfigManager;
import io.cucumber.java.BeforeAll;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

/**
 * Writes Allure's {@code environment.properties} once per test run so the
 * generated report clearly shows which base URL the scenarios were executed
 * against.
 */
public final class Hooks {

    @BeforeAll
    public static void writeAllureEnvironmentInfo() {
        ConfigManager config = ConfigManager.getInstance();

        Properties properties = new Properties();
        properties.setProperty("Base_URL", config.getBaseUrl());

        Path resultsDirectory = Path.of(System.getProperty("allure.results.directory", "target/allure-results"));
        try {
            Files.createDirectories(resultsDirectory);
            try (OutputStream out = Files.newOutputStream(resultsDirectory.resolve("environment.properties"))) {
                properties.store(out, "Auto-generated by Hooks#writeAllureEnvironmentInfo");
            }
        } catch (IOException e) {
            throw new IllegalStateException("Failed to write Allure environment.properties", e);
        }
    }
}
